# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve -l -H localhost`. If you change this file, please restart the 
# server process.
# Basic Site Settings
locale                   : "en-US"
title                    : "Gino's Homepage"
title_separator          : "-"
name                     : &name "Your Name"
description              : &description "PhDc in Psychology"
url                      : https://ginomarttelo.github.io # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : "/carmonadiaz.github.io" # the subpath of your site, e.g. "/blog"
repository               : "academicpages/academicpages.github.io"
# Site Author - The following control what appear as part of the author content on the side bar.
#               If a field is blank the icon and link will not appear, otherwise it will be shown.
#               Additional customization can be done by editing /_includes/author-profile.html
author:
  # Biographic information
  avatar           : "https://avatars.githubusercontent.com/u/85708522?v=4"
  name             : "Gino M. Carmona-Díaz"
  pronouns         : # example: "she/her"  
  bio              : "Ph.D.c in Psychology"
  location         : "Medellín"
  employer         : "Universidad Externado de Colombia"
  uri              : # URL
  email            : "mailto:g.carmona@uniandes.edu.co?subject=Collaboration&body=Hey%20Gino.%20%0A%0AI'm%20ready%20to%20work%20with%20you!"
  # Academic websites
  arxiv            : # URL - Update with the correct link to your profile
  googlescholar    : "https://scholar.google.es/citations?user=fzyBK8YAAAAJ&hl=es&oi=sra"{:target="_blank"}
  impactstory      : # URL
  orcid            : "https://orcid.org/0000-0003-2621-2557"{:target="_blank"}
  semantic         : # URL
  pubmed           : #"https://www.ncbi.nlm.nih.gov/pubmed/?term=john+snow"
  researchgate     : # URL
  # Repositories and software development
  bitbucket        : # Username - Update with your username on the site
  codepen          : # Username
  dribbble         : # Username
  github           : "https://github.com/GinoMarttelo"{:target="_blank"}
  kaggle           : # Username  
  stackoverflow    : # User number or user number and name (i.e., use "1" or "1/jeff-atwood")    

  # Social media
  #bluesky          : # Replace this with you Bluesky username
  facebook         : # Username
  flickr           : # Username
  foursquare       : # Username
  goodreads        : # Username
  google_plus      : # Username
  keybase          : # Username
  instagram        : # Username
  lastfm           : # Username
  linkedin         : # Username
  mastodon         : # URL
  medium           : # URL
  pinterest        : # Username
  soundcloud       : # Username
  steam            : # Username
  telegram         : # URL
  tumblr           : # Username
  twitter          : # Username for X / Twitter
  vine             : # Username
  weibo            : # Username
  wikipedia        : # Username
  xing             : # Username
  youtube          : # Username
  zhihu            : # URL
# Site Settings
teaser                   :  # filename of teaser fallback teaser image placed in /images/, .e.g. "500x300.png"
breadcrumbs              : false # true, false (default)
words_per_minute         : 160
future                   : true
read_more                : "disabled" # if enabled, adds "Read more" links to excerpts
talkmap_link             : false #change to true to add link to talkmap on talks page
comments:
  provider               : # false (default), "disqus", "discourse", "facebook", "google-plus", "staticman", "custom"
  disqus:
    shortname            :
  discourse:
    server               : # https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963 , e.g.: meta.discourse.org
  facebook:
    appid                :
    num_posts            : # 5 (default)
    colorscheme          : # "light" (default), "dark"
staticman:
  allowedFields          : ['name', 'email', 'url', 'message']
  branch                 : "gh-pages" # "master", "gh-pages"
  commitMessage          : "New comment."
  filename               : comment-{@timestamp}
  format                 : "yml"
  moderation             : true
  path                   : "_data/comments/{options.slug}"
  requiredFields         : ['name', 'email', 'message']
  transforms:
    email                : "md5"
  generatedFields:
    date:
      type               : "date"
      options:
        format           : "iso8601" # "iso8601" (default), "timestamp-seconds", "timestamp-milliseconds"
atom_feed:
  hide                   : false     # change to true to hide the RSS feed in the footer
  path                   : # blank (default) uses feed.xml
# SEO Related
google_site_verification :
bing_site_verification   :
alexa_site_verification  :
yandex_site_verification :
# Social Sharing
twitter:
  username               : &twitter
facebook:
  username               :
  app_id                 :
  publisher              :
og_image                 :  # Open Graph/Twitter default site image
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : # Person or Organization (defaults to Person)
  name                   : # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles
# Analytics
analytics:
  provider               :  "false" # false (default), "google", "google-universal", "google-analytics-4", "custom"
  google:
    tracking_id          :
# Reading Files
include:
  - .htaccess
  - _pages
  - files
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - config
  - gulpfile.js
  - log
  - node_modules
  - package.json
  - tmp
  - vendor
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false
# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
# Collections
collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/
# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  # _teaching
  - scope:
      path: ""
      type: teaching
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  # _publications
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  # _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: true
      share: true
      comment: true
  # _talks
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
      author_profile: true
      share: true
# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style
# Outputting
permalink: /:categories/:title/
# paginate: 5 # amount of posts to show
# paginate_path: /page:num/
timezone: America/Los_Angeles # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from
# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples)
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path/my-awesome-category/index.html ~> path: /
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
# https://github.com/jekyll/jekyll-archives
# jekyll-archives:
#   enabled:
#     - categories
#     - tags
#   layouts:
#     category: archive-taxonomy
#     tag: archive-taxonomy
#   permalinks:
#     category: /categories/:name/
#     tag: /tags/:name/
# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development
  2 changes: 1 addition & 1 deletion2  
_pages/publications.md
Original file line number	Diff line number	Diff line change
@@ -7,7 +7,7 @@ author_profile: true

{% if site.author.googlescholar %}

<div class="wordwrap">You can also find my articles on <a href="https://scholar.google.es/citations?user=fzyBK8YAAAAJ&hl=es&oi=sra"target="_blank">my Google Scholar profile</a>.</div>  
<div class="wordwrap">You can also find my articles on <a href="https://scholar.google.es/citations?user=fzyBK8YAAAAJ&hl=es&oi=sra" target="_blank">my Google Scholar profile</a>.</div>  
{% endif %}
{% include base_path %}

  2 changes: 1 addition & 1 deletion2  
_publications/moral_persuasion.md
Original file line number	Diff line number	Diff line change
@@ -5,7 +5,7 @@ permalink: /publication/moral_persuasion
excerpt: 'This study analyses the impact of argument quality and source expertise on moral persuasion, as well as the change of a moral judgment as a function of a persuasive message. Research on the effects of argument quality and source expertise on moral persuasion is scarce, although the theories of Social Intuitionism, Dual Process and Moral Convictions suggest some hints in this regard. To study the impact of these factors on moral persuasion, an experimental study was carried out with a 2 (source expertise) x 2 (argument quality) factorial design with 433 participants. A particularly sensitive moral dilemma was designed to contrast the moral foundations of Harm-Care and Justice-Reciprocity in the context of the post-conflict in Colombia to evaluate moral judgment and potential change of judgment. The results show that although most of the participants presented resistance to persuasion, both the quality of the argument and the expertise of the source facilitated persuasion, albeit independently. Results also suggest several reflections on both dual process theories of persuasion and theories of moral judgement.'
date: 2021-10-01
venue: 'Acta Colombiana de Psicología'
paperurl: 'http://carmonadiaz.github.io/files/paper1.pdf'
#paperurl: 'http://carmonadiaz.github.io/files/paper1.pdf'
citation: 'Carmona Díaz, G. M., Villada Zapata, J., Piñeres, J. D., & Jiménez Leal, W. (2021). Persuasión moral en el marco del posconflicto en Colombia: un estudio sobre la calidad de los argumentos y la experticia de la fuente. <i>Acta Colombiana de Psicología, 24</i>(2), 144-155.'

---
0 comments on commit 35c8adf
@GinoMarttelo
Comment
 
Leave a comment
 
 You’re not receiving notifications from this thread.
Footer
© 2024 GitHub, Inc.
Footer navigation
Terms
Privacy
Security
Status
Docs
Contact
Manage cookies
Do not share my personal information
ultimos · GinoMarttelo/carmonadiaz.github.io@35c8adf 